# Setup
title: "Paul Devleeschouwer"
description: "Site académique - Paul Devleeschouwer"
url: "https://pauldevleeschouwer.github.io"
baseurl: ""

# Site Author
author:
  name: "Paul Devleeschouwer"
  bio: "Étudiant en Master 1 Mathématiques et Applications à Sorbonne Université"
  location: "Paris, France"
  employer: "Sorbonne Université"
  email: "paul.devleeschouwer@etu.sorbonne-universite.fr"
  uri: "https://pauldevleeschouwer.github.io"
  # twitter: "username"
  # github: "pauldevleeschouwer"
  # googlescholar: "id"

# Site Settings
locale: "fr-FR"
encoding: "utf-8"

# Jekyll configuration
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Math typesetting
mathjax: true

# Collections settings
collections:
  publications:
    output: true
    permalink: /publications/
  teaching:
    output: true
    permalink: /teaching/
  talks:
    output: true
    permalink: /talks/

# Defaults
defaults:
  # _publications
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "single"
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "single"
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "single"
      author_profile: true
